api_version = "2025-10"

[[extensions]]
name = "B2B Credit Validation"
handle = "b2b-credit-validation"
type = "ui_extension"
uid = "d06b9508-864f-e2c8-0cda-d1c2691006dd1c4f67f4"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"
